### ISSUE TITLE
System error 1400

### ISSUE THREAD

**Issue by alconlabs** [viniciussanchez/wait-vcl#7]
Error when try create form.

procedure TFrmMain.Button2Click(Sender: TObject);
var
form:TForm;
begin
  TWait.Create('Espere...').Start(
    procedure
    begin
      form:=TfrmTest.Create(self);
      form.Show;
      //Sleep(1500); // Your code here!!!
    end);
end;

sometimes show form but without components like buttons labels etc. using delphi Berlin.

**Comment by viniciussanchez** [comment]
Hello, you are trying to manipulate a visual object (Form) within a thread (Wait). It's not allowed. This is a Delphi lock. For this you have to use synchronize.

**Comment by alconlabs** [comment]
Ok, thanks, my bad.

**Comment by alconlabs** [comment]
Hello im sorry  but how to use the syncronize to open forms (form.create ) with wait vcl class im trying but not work for me.  please i need example, thanks . 
PD: I trying to preloading to open form with data module connecting database and get large data please. Thanks you.
